services:
  timestation:
    image: ghcr.io/sniffy1988/timestation:latest
    ports:
      - target: 356
        published: 356
        protocol: tcp
    environment:
      NTP_SERVER: 10.10.20.20
    restart: unless-stopped
