services:
  timestation:
    image: ghcr.io/sniffy1988/timestation:latest
    ports:
      - target: 356
        published: 356
        protocol: tcp
      - target: 357
        published: 357
        protocol: tcp
    environment:
      CHRONY_DISABLE: "true"
      TLS_SAN: "DNS:localhost,IP:127.0.0.1,IP:10.10.20.22"
    restart: unless-stopped
