server {
    listen 356;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    add_header Cross-Origin-Opener-Policy same-origin always;
    add_header Cross-Origin-Embedder-Policy require-corp always;

    location ~ ^/serverTime\.[0-9a-z]+$ {
        if ($request_method = HEAD) {
            return 204;
        }
        return 404;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
